name: Deploy Pollen Collector (Prod)

on:
  release:
    types: [created]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-service.yml
    with:
      service_name: pollen-collector-job
      image_name: pollen-collector
      dockerfile_path: services/pollen-collector/Dockerfile
      deploy_type: jobs
      environment: production
